feat(consonant-blocks): article blocks added
adobe/pages pull request #425
Opened 2022-01-17 21:43 UTC by So1ene

- XD Spec: https://xd.adobe.com/view/7bed0802-e0e1-4b31-a348-01fd945980db-2ebe/screen/1df30115-92b1-48c8-8698-001a99d7d4dc/specs/
- Test URL: https://consonant-blocks--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/articles/article-example

### Article Blocks Added: ###
- Title
![image](https://user-images.githubusercontent.com/62023521/149839657-5d0bef32-d8ed-492a-86a5-12c867f72fb3.png)
- Images 
![image](https://user-images.githubusercontent.com/62023521/149839688-88dcb89a-f914-45c5-bf5e-8e5dc60dfa93.png)
- Textbody
- Quote (with a Gray variant)
- List
![image](https://user-images.githubusercontent.com/62023521/149839787-8e664750-4950-4690-96d8-6c2465b34aa3.png)
- Share
- Tags
![image](https://user-images.githubusercontent.com/62023521/149839850-9f49803b-d270-44e2-b23e-03e88dd2a60f.png)

2022-01-18 17:06 UTC, seanchoi-workfront requested changes
Mostly looking great, I found few things aren't matching with XD. Please take a look.

2022-01-18 17:06 UTC, seanchoi-workfront commented on templates/consonant/blocks/images/images.css
> +
Specially under the cards-horizontal, it looks off the desgin.

Your result:
![image](https://user-images.githubusercontent.com/55804872/149983731-4d989c93-e0fc-4e8b-93bd-57a366e4dd14.png)

XD:
![image](https://user-images.githubusercontent.com/55804872/149983805-2da9247a-9f61-48cb-8f67-b89416cfc522.png)

2022-01-18 22:43 UTC, So1ene commented
> Mostly looking great, I found few things aren't matching with XD. Please take a look.

Thank you for your feedback, I made the fixes, please look again when you get the chance :) @seanchoi-workfront

2022-01-19 17:08 UTC, seanchoi-workfront approved these changes
Looks good

2022-01-19 17:09 UTC, merged