learn-more-smart-block
adobe/pages pull request #438
Opened 2022-03-01 03:29 UTC by ispykenny

Example:
https://learnmore-smart-block--pages--adobe.hlx3.page/cc-growth-sandbox/test/cass-file-hero

2022-03-02 22:36 UTC, ispykenny commented
Hey @seanchoi-workfront , can you take a look at this? TIA!

2022-03-03 17:44 UTC, seanchoi-workfront requested changes

2022-03-03 17:44 UTC, seanchoi-workfront commented on pages/blocks/learnmoresmart/learnmoresmart.js
> +  const videoUrl = doc.querySelector('.youtube-dark a').getAttribute('href').split('.be/')[1];
Is this always going to be youtube-dark class?

2022-03-03 17:44 UTC, seanchoi-workfront commented on pages/blocks/learnmoresmart/learnmoresmart.js
> +        }),
This is good enough but, I would grab just `plain.html` instead whole doc.
For example fetch `https://main--pages--adobe.hlx3.page/cc-growth-sandbox/test/cass-file-hero-b.plain.html` would give you just body contents instead whole html and head contents.

2022-03-03 17:44 UTC, seanchoi-workfront commented on pages/blocks/learnmoresmart/learnmoresmart.css
> +}
You should specify .learnmoresmart class as well to avoid potential issue with other block in case they use same class name.

2022-03-03 17:44 UTC, seanchoi-workfront commented on pages/blocks/learnmoresmart/learnmoresmart.css
> +  .learn-content {
Same as above.

2022-03-03 17:46 UTC, seanchoi-workfront commented
> Hey @seanchoi-workfront , can you take a look at this? TIA!

I reviewed with some comments. Can you also tell me where you got this request?

2022-03-03 19:43 UTC, ispykenny commented
Hey @seanchoi-workfront thanks for the feedback. That all made sense. I have implemented the changes. Please take a look when you're able to. Thank you.

2022-03-03 21:24 UTC, seanchoi-workfront approved these changes

2022-03-03 21:27 UTC, seanchoi-workfront commented
> 

@ispykenny I approved this PR. Would you please let me know where you got this request?

2022-03-03 22:33 UTC, merged