chore(sidekick): prepare for manifest v3 version
adobe/pages pull request #483
Opened 2022-07-04 12:44 UTC by rofe

2022-07-10 18:56 UTC, rofe commented on tools/sidekick/plugins.js
> +};
@davidnuescheler do you know if this sidekick extension is still needed? It looks like something from pre-hlx3 times...

2022-07-12 08:33 UTC, rofe commented on tools/sidekick/plugins.js
> +};
I'll remove it for now.

2022-07-16 04:08 UTC, amauch-adobe commented
I'm assuming for testing this PR these would be the instructions.  I'm pulling these comments from your PR in the FedPub repo.

https://sidekick-mv3--fedpub--adobe.hlx.page/creativecloud/photography/hub/guides/guide-to-aperture-vs-iris

To try it out, create a local checkout of the [helix-sidekick-extension](https://github.com/adobe/helix-sidekick-extension) repo, switch to the mv3 branch and follow these instructions:
https://github.com/adobe/helix-sidekick-extension#local-testing

cc @rofe

2022-07-16 06:35 UTC, amauch-adobe requested changes
@rofe, I followed your instructions for testing this out, meaning I installed the mv3 version of the helix sidekick by using the branch specified. I then added the Pages (PACOM) site to the helix sidekick extension and then went to this URL (https://pages.adobe.com/lightroom/en/wg/lightroom-mobile-feedback) for testing. When I did that I no longer could see the different plugin buttons specific to the PACOM config.json in your PR, meaning on the preview view the "Parent Folder" button was no longer there and also was gone when in edit mode/view. I noticed the "Parent Folder" was a specific config option according to the JSON so I was wondering why it wasn't showing up for the helix sidekick mv3 version?

Other than that concern, everything else looked good.

2022-08-22 14:54 UTC, rofe commented
@amauch-adobe is it working on https://main--pages--adobe.hlx.page/lightroom/en/wg/lightroom-mobile-feedback?

Note that the parent folder plugin is currently configured to only show up in the `dev` and `preview` environments. If you need it for `live` and/or `prod` as well, you can add them to the `environments` array in `config.json`.

2022-08-22 14:58 UTC, rofe commented
Sorry, this can of course only be tested on the `sidekick-mv3` branch of this project, so you would need to set your sidekick to use `https://github.com/adobe/pages/tree/sidekick-mv3` as GitHub URL and then come here:

https://sidekick-mv3--pages--adobe.hlx.page/lightroom/en/wg/lightroom-mobile-feedback

2022-08-28 12:40 UTC, rofe commented
@amauch-adobe have you been able to test this with the updated instructions above?

2022-08-31 00:50 UTC, amauch-adobe approved these changes
Everyone looks good now.

2022-09-11 18:54 UTC, merged